import { v4 as uuidv4 } from "uuid";

export const FICHAS = [
  {
    id: uuidv4(),
    voltear: false,
    imagen: "300ds",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "625dsx",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "790",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "1250gs",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "cb500",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "duke",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "g310gs",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "monster",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "mt09",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "ninja",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "r1",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "tracer900",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "versys",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "xadv",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "300ds",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "625dsx",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "790",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "1250gs",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "cb500",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "duke",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "g310gs",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "monster",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "mt09",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "ninja",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "r1",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "tracer900",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "versys",
    resuelto: false,
  },
  {
    id: uuidv4(),
    voltear: false,
    imagen: "xadv",
    resuelto: false,
  },
];
